; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28314.0 

	TITLE	D:\GitHub Repos\CPP-Intro\CPP-BasicToAdvanced\CPP-BasicToAdvanced\Math.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__2AE05F36_Math@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?Log@@YAPBDPBD@Z				; Log
PUBLIC	?Multiply@@YAHHH@Z				; Multiply
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_0P@OAEMKLFP@Multiplication@		; `string'
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
;	COMDAT ??_C@_0P@OAEMKLFP@Multiplication@
CONST	SEGMENT
??_C@_0P@OAEMKLFP@Multiplication@ DB 'Multiplication', 00H ; `string'
CONST	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?Multiply@@YAHHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?Multiply@@YAHHH@Z PROC					; Multiply, COMDAT
; File D:\GitHub Repos\CPP-Intro\CPP-BasicToAdvanced\CPP-BasicToAdvanced\Math.cpp
; Line 9
	push	ebp
	mov	ebp, esp
	sub	esp, 64					; 00000040H
	push	ebx
	push	esi
	push	edi
	mov	ecx, OFFSET __2AE05F36_Math@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 10
	push	OFFSET ??_C@_0P@OAEMKLFP@Multiplication@
	call	?Log@@YAPBDPBD@Z			; Log
	add	esp, 4
; Line 11
	mov	eax, DWORD PTR _a$[ebp]
	imul	eax, DWORD PTR _b$[ebp]
; Line 12
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?Multiply@@YAHHH@Z ENDP					; Multiply
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?Log@@YAPBDPBD@Z
_TEXT	SEGMENT
_message$ = 8						; size = 4
?Log@@YAPBDPBD@Z PROC					; Log, COMDAT
; File D:\GitHub Repos\CPP-Intro\CPP-BasicToAdvanced\CPP-BasicToAdvanced\Math.cpp
; Line 4
	push	ebp
	mov	ebp, esp
	sub	esp, 64					; 00000040H
	push	ebx
	push	esi
	push	edi
	mov	ecx, OFFSET __2AE05F36_Math@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 5
	mov	eax, DWORD PTR _message$[ebp]
; Line 6
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?Log@@YAPBDPBD@Z ENDP					; Log
_TEXT	ENDS
END
